### ISSUE TITLE
When installing an error

### ISSUE THREAD

**Issue by TorBax** [turnermm/htmlOKay#3]
if the folder content is different from  _data_

/data/pages/ is not readable (htmlOkay, line 225)

**Comment by turnermm** [comment]
You don't say line 225 of which file.  
The plugin was not designed for wikis with alternate save directories.  But you can try setting the correct path in action.php and admin.php:

```
action.php:5:if(!defined('HTMLOK_WIKI_PATH'))define ('HTMLOK_WIKI_PATH', DOKU_INC . 'data/pages/');
admin.php:10:if(!defined('HTMLOK_WIKI_PATH'))define ('HTMLOK_WIKI_PATH', DOKU_INC . 'data/pages');

```
For `DOKU_INC . 'data/pages'` substitute your own path.
