### ISSUE TITLE
wrong Files are shown in HTML Access Manager

### ISSUE THREAD

**Issue by a3sir** [turnermm/htmlOKay#4]
As the title says in the Access Manager you can select the namespace from the dropdown list and click on select, the namespace name on the right side of the files row is updated but the list of files is not. It always shows the files of the root namespace so you can't change permissions for files that are not directly under root.

**Comment by turnermm** [comment]
I'm not clear what you mean by right side, but see this:
http://www.youtube.com/watch?v=Pwybf32knQc

**Comment by a3sir** [comment]
Hey, with the right side I meant the name of the namespace in the files row (no. 1 in the attachment).
But the files list does not change (no. 2 in the attachment), it alway shows the files in the root namespace.
I also reinstalled the plugin, but nothing changed. Strange, maybe its a conflict with another plugin.
![html access - marked](https://user-images.githubusercontent.com/7288786/31779410-546eb7d0-b4f3-11e7-9933-794367312f56.jpg)

**Comment by turnermm** [comment]
As you can see from the video I am not getting this result.  Try clearing your browser cache and refreshing your dokuwiki cache:  https://www.dokuwiki.org/caching

**Comment by a3sir** [comment]
I cleared the cache but that did not help. I completely deleted the plugin and installed it again, now it works  if I click save again after clicking select to change the namespace. Although it's not quite like in the video for me it works this way now.
