### ISSUE TITLE
Html does not work on allowed pages

### ISSUE THREAD

**Issue by a3sir** [turnermm/htmlOKay#5]
I have a strange problem with allowing html. Most of the time I see just the html code on allowed pages instead of the rendered output. If I change something on the page, no matter how unimportant the change is (i.e. a space at the end) and save, the correct output is shown but only for one time. If I refresh the page I see the code again. I couldn't find out what the problem is. I cleared the cache of the wiki and the browser several times, ich tried different browsers and PCs, i disabled every plugin and reenabled them one by one to check if there are any conflicts. Disabling and enabling plugins makes the page also work for one time an then it doesn't work anymore. I even disabled the template to see if it works with the standard template of Dokuwiki but that didn't do anything either. The only thing that worked partially ist to add the "purge=true" parameter beheind the url and then refresh with ctrl+f5. That works every time. Then I tried to use the ~NOCACHE~ statement on the page, but that didn't work. I don't know what to try anymore. Maybe someone else has an idea.

**Comment by turnermm** [comment]
Is the `htmlok` configuration option set to true?  And have you tried to disable htmlokay plugin?

**Comment by a3sir** [comment]
Yes, htmlok is set to true. When I disable htmlokay plugin the html code works just fine. I also reinstalled the plugin multiple times with clearing the cache in between but nothing changed.

**Comment by turnermm** [comment]
I don't think I can help you.  htmlokay is 10 years old and may not function correctly any longer under certain conditions.  At some point I may have the time to go back to it, but not currently.
